version: '3.8'
services:
  node:
    container_name: ${COMPOSE_PROJECT_NAME}_node
    build:
      context: .
      args:
        USER_ID: ${UID} # Assurez-vous de définir l'UID dans votre environnement
    volumes:
      - ./app:/app
    ports:
       - "3000:3000"
    environment:
      - NODE_ENV=development
